Add cli flag to change the backup basedir
canonical/juju-backup-all pull request #50
Opened 2024-07-02 08:38 UTC by chanchiwai-ray

Add command line flag to change the backup basedir. 

This provide a potential workaround if the disk of the application machine is full, or the default backup directory is not writable.

fixes: #49

2024-07-02 13:21 UTC, rgildein submitted a review, later dismissed
LGTM

2024-07-02 13:21 UTC, rgildein commented on jujubackupall/process.py
> +        app_backup_basedir: Path = Path("/home/ubuntu"),
nit: Can we define this as constant?

2024-07-02 13:40 UTC, gabrielcocenza requested changes

2024-07-02 13:40 UTC, gabrielcocenza commented on jujubackupall/backup.py
> +        if self.backup_basedir is not None:
I'm not understanding the need of this if condition because it will never be None. I think it can always run the mkdir command with the -p flag

2024-07-02 13:40 UTC, gabrielcocenza commented on jujubackupall/backup.py
> +        return SwiftBackup(unit=unit, backup_basedir=backup_basedir)
Can we open a separate PR to remove SwiftBackup? This is a dummy class and there is no action to do any backup.

2024-07-02 13:40 UTC, gabrielcocenza commented on jujubackupall/backup.py
> +        self.backup_filepath = target
```suggestion
        self.backup_filepath = self.backup_basedir / self.pgdump_filename
        backup_cmd = f"sudo -u postgres pg_dumpall | gzip > {self.backup_filepath}"
        ssh_run_on_unit(unit=self.unit, command=backup_cmd)
```

2024-07-02 13:40 UTC, gabrielcocenza commented on jujubackupall/config.py
> +        return self.args.get("basedir")
Don't you need to change the `dest` on `--app-backup-basedir` to `basedir` to be able to get this?

2024-07-02 13:40 UTC, gabrielcocenza commented on jujubackupall/cli.py
> +    parser.add_argument(
I think you'll need to add this new argument into the dictionary at `_parse_args`.
Looks like is not a good design

2024-07-03 01:21 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        return SwiftBackup(unit=unit, backup_basedir=backup_basedir)
thb, this should not be a cli at all since it's internal to how thing works, and not relevant to the end user. The DB charms itself should handle disk full kind of situation, but if we want to fix it this way, creating one-for-all or one-to-one (like you mentioned) args is the only way. 

However, I don't think we should offer one-to-one because it will just make thing more complicated. WDYT?

2024-07-03 01:35 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        return SwiftBackup(unit=unit, backup_basedir=backup_basedir)
How about in the charm, do you think it would be good to have per application ?

2024-07-03 01:49 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        return SwiftBackup(unit=unit, backup_basedir=backup_basedir)
so this is why I was saying should we need to be more precise about the issue we want to fix: currently this issue only happens to postgresql. And I think we should just add cli flag to postgresl, and not per application

2024-07-03 02:05 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        return SwiftBackup(unit=unit, backup_basedir=backup_basedir)
agree

2024-07-03 02:25 UTC, jneo8 commented on jujubackupall/backup.py
> +        return SwiftBackup(unit=unit, backup_basedir=backup_basedir)
Can we create an issue to provide this separate arguments to different applications?
I see your point that we shouldn't use the same backup-dir for all the application, but it doesn't means the situation, *no space left*, wouldn't happen on those applications.

2024-07-03 02:42 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        return SwiftBackup(unit=unit, backup_basedir=backup_basedir)
Since the issue is updated, I will add per db cli flag

2024-07-03 02:50 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        if self.backup_basedir is not None:
it can be `None` if one decided to pass `backup_basedir = None`

2024-07-03 03:53 UTC, chanchiwai-ray commented on jujubackupall/process.py
> +        app_backup_basedir: Path = Path("/home/ubuntu"),
Done

2024-07-03 03:54 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        if self.backup_basedir is not None:
Anyway, change to always running the command

2024-07-03 03:54 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        self.backup_filepath = target
yeah, not sure why it was like that before, updating

2024-07-03 03:55 UTC, chanchiwai-ray commented on jujubackupall/config.py
> +        return self.args.get("basedir")
thanks, updated

2024-07-03 03:55 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        self.backup_filepath = target
thanks, that's tricky to see, updated

2024-07-03 03:56 UTC, chanchiwai-ray commented on README.md
> +base directory for the applications:
updated

2024-07-03 03:56 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        return SwiftBackup(unit=unit, backup_basedir=backup_basedir)
Updated

2024-07-03 03:57 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        return SwiftBackup(unit=unit, backup_basedir=backup_basedir)
I don't have bandwidth to remove it opening an issue: https://github.com/canonical/juju-backup-all/issues/51

2024-07-03 03:58 UTC, chanchiwai-ray commented on jujubackupall/cli.py
> +    parser.add_argument(
Yes, indeed

2024-07-03 06:58 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        ssh_run_on_unit(unit=unit, command=f"mkdir -p {self.backup_basedir}")
hmm, yeah the problem is not the root, mysql charm has its own logic to create directory, and it's owned by `mysql:mysql`. The default file creation in the charm code is `root:root`

2024-07-03 07:07 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        ssh_run_on_unit(unit=unit, command=f"mkdir -p {self.backup_basedir}")
Yeah, in fact both mysql and etcd create the backup dir, so I will move this code to postgresql only

2024-07-03 07:08 UTC, chanchiwai-ray commented on jujubackupall/process.py
> +        :param backup_location_on_etcd: backup localtion on etcd unit
Thanks, fixed

2024-07-03 07:08 UTC, chanchiwai-ray commented on README.md
> +vaules.
Thanks, fixed

2024-07-03 08:55 UTC, jneo8 submitted a review, later dismissed
LGTM

2024-07-03 13:34 UTC, gabrielcocenza approved these changes
LGTM, but please add the info that etcd and mysql are able to create the backup folders

2024-07-03 13:34 UTC, gabrielcocenza commented on jujubackupall/backup.py
> +        ssh_run_on_unit(unit=unit, command=f"mkdir -p {self.backup_basedir}")
Can you add this information for future travelers?

2024-07-04 01:23 UTC, chanchiwai-ray commented on jujubackupall/backup.py
> +        ssh_run_on_unit(unit=unit, command=f"mkdir -p {self.backup_basedir}")
added

2024-07-04 03:38 UTC, samuelallan72 reviewed
Looks good, pending functional tests.  Have you also tested this yourself on a deployment of the three db charms? :)

2024-07-04 03:38 UTC, samuelallan72 commented on README.md
> +backup base directory for the unit.
nit: could also mention that directories are created here:

```suggestion
backup base directory for the unit. Directories will be created if needed.
```

2024-07-04 07:33 UTC, chanchiwai-ray commented on README.md
> +backup base directory for the unit.
done

2024-07-04 07:34 UTC, chanchiwai-ray commented
> Looks good, pending functional tests. Have you also tested this yourself on a deployment of the three db charms? :)

Wait for func test

2024-07-04 07:37 UTC, samuelallan72 approved these changes

2024-07-04 09:39 UTC, jneo8 approved these changes

2024-07-04 23:10 UTC, samuelallan72 commented on jujubackupall/process.py
> +        app_backup_basedir: Path = Path("/home/ubuntu"),
resolving because a lot has changed since this comment, and default paths are now constants.

2024-07-05 07:43 UTC, merged